### ISSUE TITLE
Why does Alfworld cause Obs to output ’Nothing happens‘ and only get it right 26% of the time after running main.py?

### ISSUE THREAD

**Issue by Old-Lorry** [PanasonicConnect/rap#8]
Why does Alfworld cause Obs to output ’Nothing happens‘ and only get it right 26% of the time after running main.py?
![1](https://github.com/user-attachments/assets/1c82f99d-0461-4ee4-ad54-10f6ecc74a97)

**Comment by tomoyukik0** [comment]
Thank you for showing interest in our work.
The output "Nothing happens" in the Observation occurs when an action is entered that the environment cannot accept.
Also, we obtained almost the same results as in the paper using the default settings, so we may be able to provide some advice if you could provide more detailed settings.

**Comment by Old-Lorry** [comment]
![image](https://github.com/user-attachments/assets/923ce13f-b989-42e9-900d-ff82ba740a5a)
![Uploading image.png…]
I appreciate your response and assistance. I utilized the GPT-4-0613 model through Azure OpenAI, adhering to the default configurations specified in the base_config.yaml file. Thank you once again for your support.

**Comment by tomoyukik0** [comment]
Thank you for your response.
We have confirmed that we can reptoduce the result using gpt-3.5-instruct, so could you please verify it with this model?
